namespace RecordTypes.YGC.Enums
{
    public enum TransactionCode
    {
        SuitRequirementsReceived = 1,
        DirectPayment = 2,
        FeesReceived = 9,
        Collection = 20,
        SettlementPayment = 22,
        SpecificFinancialTransaction_1 = 51,
        SpecificFinancialTransaction_2 = 52,
        SpecificFinancialTransaction_3 = 53,
        SpecificFinancialTransaction_4 = 54,
        SpecificFinancialTransaction_5 = 55,
        SpecificFinancialTransaction_6 = 56,
        SpecificFinancialTransaction_7 = 57,
        SpecificFinancialTransaction_8 = 58,
        SpecificFinancialTransaction_9 = 59,
        SpecificFinancialTransaction_10 = 60,
        SpecificFinancialTransaction_11 = 61,
        SpecificFinancialTransaction_12 = 62,
        SpecificFinancialTransaction_13 = 63,
        SpecificFinancialTransaction_14 = 64,
        SpecificFinancialTransaction_15 = 65,
        SpecificFinancialTransaction_16 = 66,
        SpecificFinancialTransaction_17 = 67,
        SpecificFinancialTransaction_18 = 68,
        SpecificFinancialTransaction_19 = 69,
        SpecificFinancialTransaction_20 = 70,
        SpecificFinancialTransaction_21 = 71,
        SpecificFinancialTransaction_22 = 72,
        SpecificFinancialTransaction_23 = 73,
        SpecificFinancialTransaction_24 = 74,
        SpecificFinancialTransaction_25 = 75,
        SpecificFinancialTransaction_26 = 76,
        SpecificFinancialTransaction_27 = 77,
        SpecificFinancialTransaction_28 = 78,
        SpecificFinancialTransaction_29 = 79,
        MiscDisbursement = 80,
        MiscCostCharge = 81,
        NewClaimEntry = 91,
        JudgmentEntered = 92,
        MiscAccountCardAdjust = 93,
        MiscFinancialTransaction = 99
    }
}
